### ISSUE TITLE
Possible memory leak(?)

### ISSUE THREAD

**Issue by sjdaws** [sabnzbd/sabnzbd#2592]
I've come across an interesting problem, not sure whether the fault lays with sabnzbd, the docker image, or kubernetes but I'll start here and see if anyone else is experiencing it. 

When downloading with SABnzbd, I'll get full speed until the amount downloaded hits the memory limit, e.g. if I set a memory limit of 2Gi I get full speed for roughly 2GB of data, 8Gi / 8GB data, 128Gi / 128GB data - once this limit is hit the download speed slows to about 1MB/s.

<img width="219" alt="Screenshot 2023-06-16 at 3 40 14 pm" src="https://github.com/sabnzbd/sabnzbd/assets/659316/7b187398-66b7-4c38-b2c1-f7c7d1b1b726">
<br><br>

I get full speed again if:
- The queue fully completes and a new item is added
- The pod is restarted

I don't get full speed if:
- I restart SABnzbd using the menu -> restart SABnzbd
- I allocate more CPU cores
- I dedicate CPU cores by setting requests = limits for CPU
- I set requests for memory lower than limit, e.g. 1Gi requests, 2Gi limits - it still drops speed at limit

I do get a speed boost if I click the wrench and refresh system stats, which are shown as little peaks here:

<img width="356" alt="Screenshot 2023-06-16 at 3 43 17 pm" src="https://github.com/sabnzbd/sabnzbd/assets/659316/6a201da7-8b6c-44a8-9eea-e86ba67aea25">

This goes back down once the stats are fetched. The fact this happens makes me wonder what is being done when refreshing the stats, is it allocating/deallocating memory?

I didn't experience this issue with SABnzbd 3.

---

Steps to replicate:

- Load manifest into kubernetes, with 2Gi memory limit
- Download 10GB test file, you get roughly 10% for free (I assume due to pars/repair?)
- Speed starts to tail off around 3GB downloaded (3016MB for first test, 3063MB for second test)

---

I have tried:

- All the settings outlined in high speed tuning
- Using caches of different sizes
- Moving everything to SSD
- A different cluster
- Putting it on it's own dedicated/tainted worker
- A fresh install of SABnzbd
- A single news server
- Changing the number of connections used on news servers
- Enabling/disabling SSL

---

**Version:** 4.0.2
**Platform:** Kubernetes 1.27.2, cri-o 1.26.0

**System statistics:**

<img width="515" alt="Screenshot 2023-06-16 at 3 52 54 pm" src="https://github.com/sabnzbd/sabnzbd/assets/659316/7a601463-125f-4c93-b571-8ef2edecf97b">
<br><br>

**Drives**:
- `/intermediate` is on an SSD RAID 10 set via DAS
- `/downloads` is on a HDD RAID 10 set via DAS, I don't believe the speed here is a limiting factor, I pause the queue for post processing. Changing this to the SSD RAID made no difference.

**Manifest**:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: sabnzbd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sabnzbd
    service: sabnzbd
  name: sabnzbd
  namespace: sabnzbd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sabnzbd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
      version: v1
  template:
    metadata:
      labels:
        app: sabnzbd
        version: v1
    spec:
      containers:
        image: docker.io/linuxserver/sabnzbd:unstable
        name: sabnzbd
        resources:
          limits:
            memory: 2Gi
```
