### ISSUE TITLE
Issues with history

### ISSUE THREAD

**Issue by modem7** [sabnzbd/sabnzbd#2767]
### SABnzbd version

4.2.0

### Operating system

Docker

### Using Docker image

linuxserver

### Description

Since upgrading to 4.2.0 items go into history until they complete, and then immediately remove themselves, which breaks integration with other tools. 

Downgrading to 4.1.0 resolves. 

There are no errors or messages in the console unfortunately that would indicate an error, download completes successfully.

```yaml
 #SABnzbd - Binary newsgrabber (NZB downloader)
  sabnzbd:
    # image: linuxserver/sabnzbd
    image: linuxserver/sabnzbd:4.1.0
    container_name: Sabnzbd
    hostname: Sabnzbd
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: linuxserver/mods:sabnzbd-par2cmdline-turbo
      # DOCKER_MODS: ghcr.io/gilbn/theme.park:sabnzbd
      # TP_THEME: Overseer
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    labels:
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.sabnzbd-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr-bypass.rule=Host(`sabnzbd.$DOMAINNAME`) && Query(`apikey`, `$SABNZBD_API_KEY`)"
      - "traefik.http.routers.sabnzbd-rtr-bypass.priority=100"
      # - "traefik.http.routers.sabnzbd-rtr-bypass.tls=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.sabnzbd-rtr.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.$DOMAINNAME`)"
      - "traefik.http.routers.sabnzbd-rtr.priority=98"
      # - "traefik.http.routers.sabnzbd-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.sabnzbd-rtr-bypass.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.sabnzbd-rtr-ping.middlewares=chain-no-auth@file"
      - "traefik.http.routers.sabnzbd-rtr.middlewares=chain-oauth-admins@file"
      # - "traefik.http.routers.sabnzbd-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc"
      - "traefik.http.routers.sabnzbd-rtr-bypass.service=sabnzbd-svc"
      # - "traefik.http.routers.sabnzbd-rtr-ping.service=sabnzbd-svc"
      - "traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080"
      ## Homepage
      - homepage.name=Sabnzbd
      - homepage.group=Download + Search
      - homepage.icon=sabnzbd
      - homepage.href=https://sabnzbd.$DOMAINNAME
      - homepage.widget.type=sabnzbd
      - homepage.widget.url=http://sabnzbd:8080
      - homepage.widget.key=$SABNZBD_API_KEY
    networks:
      pihole:
        ipv4_address: '172.22.0.103'
    healthcheck:
      test: curl -fSs 127.0.0.1:8080/api?mode=version || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    ports:
      - "25916:8080"
    volumes:
      - $USERDIR/Sabnzbd:/config
      - $DOWNLOADDIR:/downloads
      - $SABDIR:/incomplete-downloads
      # - $DOWNLOADDIR:/incomplete-downloads
      # - $RAMDRIVEPLEX/sab:/incomplete-downloads
    restart: always
```
