### ISSUE TITLE
_FAILED_ folders not being deleted properly?

### ISSUE THREAD

**Issue by engels74** [sabnzbd/sabnzbd#2840]
### SABnzbd version

4.2.3 [e7e06de]

### Operating system

Ubuntu 22.04.4 LTS (VM through UnraidOS)

### Using Docker image

hotio

### Description

Hello 👍 

I used SABnzbd for many years, so first of I just wanted to say a massive thank you for maintaining and improving this app over the years ❤️ . Very grateful.

My setup is the usual "arr" setup. Adding series to Sonarr -> Prowlarr searches, returns downloads to Sonarr -> SABnzbd downloads -> Sonarr imports -> Available on my personal Media Server. Sonarr is set to both "**Remove Completed**" and "**Remove Failed**" in the SABnzbd settings.

Anyways, I've had an odd experience today. I had a _massive_ list of episodes from a single TV series, that was in my SABnzbd queue. All the downloads failed, I'm guessing either it was taken down from Usenet or some unpacking error.

But after the downloads failed, and Sonarr had removed the failed downloads from its history, **all** of the folders were kept in the "completed" download directory. In my case, and since it's Sonarr, it's `/data/mount/stage/.usenet/completed/sonarr`. Like 100GBs of _FAILED_ folders, with two files inside: One `.mkv` file of 0 bytes, and a `.zip` archive of 5-10GB. All of the folders had one `.mkv` and a multiple-GB `.zip` file in there.

My cleanup list in SABnzbd doesn't contain "zip", as I'm not sure if that would affect the unpacking process?

**Current SABnzbd settings:**
I redacted the parts from my `sabnzbd.ini` file, and it's available here:
https://logs.notifiarr.com/?21193d7bd72458d1=#F4BEedxx582BMY3mCRAoqbWRc859yA8tUDKPGkEn16PE

If that doesn't work out, here's some screenshots of each of my SABnzbd settings pages:
- [General](https://i.imgur.com/ThwXzEb.png)
- [Folders](https://i.imgur.com/EnF7G1j.png)
- [Servers](https://i.imgur.com/c4GBw7H.png)
- [Categories](https://i.imgur.com/xWTK1n7.png)
- [Switches](https://i.imgur.com/M0DjHTf.png)

The rest I haven't changed, so not attaching screenshots of that

**Docker Compose (hotio):**
```yaml
name: download-tools
services:
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
      - TP_HOTIO=true
      - TP_THEME=dark
    volumes:
      - /opt/docker-all/downloadTools/sabnzbd:/config
      - /data:/data
      - /data/scripts/themepark/98-themepark-sabnzbd:/etc/cont-init.d/98-themepark
    restart: unless-stopped
```

**Logs of the affected series:** (look for `My.Favorite.Series` or `MY FAVORITE SERIES`)
Link: (huge file)
https://logs.notifiarr.com/?6c6ec2d15047da7d#FcmZ7E4ggB3JrNEAZLficEztAsykCaUrK7hR8cPdGNxC

It says this:
``` 
2024-04-22 02:50:42,899::INFO::[nzbstuff:1806] [N/A] Purging data for job My.Favorite.Series.S07E10.Multi.1080p.BluRay.DTS-HDMA (delete_all_data=False)
```

for each folder, but all of the `_FAILED_` folders were still there, including the large `.zip` file and the empty `.mkv` file.
It was specifically *all* of the `My.Favorite.Series.SXXEXX.Multi.1080p.BluRay.DTS-HDMA` that was "left behind", or just not deleted / removed completely.

**Question:**
What have I done wrong? I haven't really experienced it ever quite like that, having hundreds of GB being left behind in the `_FAILED_` folders. Should I set up my "Cleanup List" to include `.zip` files, or is it somewhere else it fails? It usually deletes `_FAILED_` folders just fine, with maybe a few weird ones once in a while, not being deleted.
