### ISSUE TITLE
LSIO Docker container v4.5.1 and 4.5.0 "Lost connection to SABnzbd" every couple minutes

### ISSUE THREAD

**Issue by mattague** [sabnzbd/sabnzbd#3088]
### SABnzbd version

4.5.1

### Operating system

Ubuntu 22.04, Debian 12 (proxmox lxc), ubuntu 24.04 (proxmox lxc), debian 12 (proxmox vm)

### Using Docker image

linuxserver

### Description

Using the hotio image, the LSIO image, and the [binhex/arch-sabnzbd](https://hub.docker.com/r/binhex/arch-sabnzbd) images, on 4 different hosts, between 2 physical machines, one of which using Librespeed, I am confirmed to have a 2.5Gbps connection to at around 1ms, and all of them with a minimum of 8 cores and 16GB of memory, I am constantly getting "Lost connection to SABnsbd" every minute or two. I was able to add all the same news servers I've been using on nzbget, setup all the folders the same way, then nothing works. I tried downloading a few files from radarr and sonarr, and sometimes the nzb gets queued, but the webui loses connection, then when it comes back the download has failed due to missing files. 

[logs](https://pastebin.com/YpkbvsPe)

compose.yaml:

```
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:amd64-4.5.0
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mattague/docker/data/sabnzb/config:/config
      - /mnt/share/media:/media
    ports:
      - 8092:8080
    restart: unless-stopped
```
