### ISSUE TITLE
Create snap file

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#856]
Requested by Canonical, if we could create a snapcraft file for ease of installation (alternative to the PPA).
Then we would have to still link to automated build process (probably based on tags).
Haven't had time to dive into it yet.

Current draft:
```yml
name: sabnzbd
version: '2.1.0'
summary: SABnzbd - The automated Usenet download tool
description: |
  SABnzbd is an Open Source Binary Newsreader written in Python.
  It's totally free, incredibly easy to use, and works practically everywhere.

grade: stable
confinement: strict

apps:
  sabnzbd:
    command: env LANG=en_US.UTF-8 python2.7 -OO $SNAP/bin/SABnzbd.py -d -f $SNAP_USER_DATA/sabnzbd.ini
    plugs:
      - network
      - network-bind

parts:
  par2:
    plugin: autotools
    source: https://github.com/Parchive/par2cmdline.git
    build-packages:
      - g++
  unrar:
    plugin: make
    source: http://archive.ubuntu.com/ubuntu/pool/multiverse/u/unrar-nonfree/unrar-nonfree_5.5.5.orig.tar.gz
    build-packages:
      - g++
  sabnzbd:
    plugin: python
    python-version: python2
    source: https://github.com/sabnzbd/sabnzbd.git
    source-branch: master
    source-depth: 1
    python-packages:
      - sabyenc
    stage-packages:
      - python-cheetah
      - python-cryptography
      - p7zip-full
      - unzip
      - python-notify2
      - python-pysqlite2
    install: cp -R . $SNAPCRAFT_PART_INSTALL/bin/ 
```
